/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import javax.swing.JOptionPane;
import main.ProductorIntro;

/**
 *
 * @author epidu
 */
public class casaRodaje extends javax.swing.JFrame {
           boolean iniciar = true;
            int maxIntro = 0;

           /**
            * Creates new form casaRodaje
            */
           public casaRodaje() {
                      initComponents();
                      this.setLocationRelativeTo(null);
                      this.setResizable(false);
           }

           /**
            * This method is called from within the constructor to initialize
            * the form. WARNING: Do NOT modify this code. The content of this
            * method is always regenerated by the Form Editor.
            */
           @SuppressWarnings("unchecked")
           // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
           private void initComponents() {

                      jPanel1 = new javax.swing.JPanel();
                      jPanel2 = new javax.swing.JPanel();
                      jLabel1 = new javax.swing.JLabel();
                      jLabel2 = new javax.swing.JLabel();
                      jLabel3 = new javax.swing.JLabel();
                      jLabel4 = new javax.swing.JLabel();
                      jLabel5 = new javax.swing.JLabel();
                      jLabel6 = new javax.swing.JLabel();
                      jSpinner1 = new javax.swing.JSpinner();
                      jSpinner2 = new javax.swing.JSpinner();
                      jSpinner3 = new javax.swing.JSpinner();
                      jSpinner4 = new javax.swing.JSpinner();
                      jSpinner5 = new javax.swing.JSpinner();
                      jLabel7 = new javax.swing.JLabel();
                      jScrollPane6 = new javax.swing.JScrollPane();
                      jTextPane6 = new javax.swing.JTextPane();
                      jCheckBox1 = new javax.swing.JCheckBox();
                      jCheckBox2 = new javax.swing.JCheckBox();
                      jCheckBox3 = new javax.swing.JCheckBox();
                      jCheckBox4 = new javax.swing.JCheckBox();
                      jCheckBox5 = new javax.swing.JCheckBox();
                      jLabel8 = new javax.swing.JLabel();
                      jSpinner6 = new javax.swing.JSpinner();
                      jLabel9 = new javax.swing.JLabel();
                      jScrollPane8 = new javax.swing.JScrollPane();
                      jTextPane8 = new javax.swing.JTextPane();
                      jLabel10 = new javax.swing.JLabel();
                      jScrollPane9 = new javax.swing.JScrollPane();
                      jTextPane9 = new javax.swing.JTextPane();
                      jLabel11 = new javax.swing.JLabel();
                      jScrollPane10 = new javax.swing.JScrollPane();
                      jTextPane10 = new javax.swing.JTextPane();
                      jLabel12 = new javax.swing.JLabel();
                      jScrollPane11 = new javax.swing.JScrollPane();
                      jTextPane11 = new javax.swing.JTextPane();
                      jLabel13 = new javax.swing.JLabel();
                      jLabel14 = new javax.swing.JLabel();
                      jScrollPane12 = new javax.swing.JScrollPane();
                      jTextPane12 = new javax.swing.JTextPane();
                      jScrollPane13 = new javax.swing.JScrollPane();
                      jTextPane13 = new javax.swing.JTextPane();
                      Simulacion = new javax.swing.JButton();
                      jLabel15 = new javax.swing.JLabel();
                      jScrollPane14 = new javax.swing.JScrollPane();
                      jTextPane14 = new javax.swing.JTextPane();
                      jLabel16 = new javax.swing.JLabel();
                      jScrollPane15 = new javax.swing.JScrollPane();
                      jTextPane15 = new javax.swing.JTextPane();
                      jLabel17 = new javax.swing.JLabel();
                      jScrollPane16 = new javax.swing.JScrollPane();
                      jTextPane16 = new javax.swing.JTextPane();
                      jLabel18 = new javax.swing.JLabel();
                      jScrollPane17 = new javax.swing.JScrollPane();
                      jTextPane17 = new javax.swing.JTextPane();
                      outputPlotTwist = new javax.swing.JLabel();
                      outputIntro = new javax.swing.JLabel();
                      outputCreditos = new javax.swing.JLabel();
                      outputInicio = new javax.swing.JLabel();
                      outputCierre = new javax.swing.JLabel();

                      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                      getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                      jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
                      getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 138, -1, -1));

                      jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
                      getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

                      jLabel1.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
                      jLabel1.setForeground(new java.awt.Color(51, 102, 255));
                      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel1.setText("Casa de Rodaje Game of Thrones");
                      getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 340, 30));

                      jLabel2.setText("Intro");
                      getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 40, -1));

                      jLabel3.setText("creditos");
                      getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

                      jLabel4.setText("inicio");
                      getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

                      jLabel5.setText("cierre");
                      getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

                      jLabel6.setText("plot twist");
                      getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
                      getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 50, -1));
                      getContentPane().add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, -1));
                      getContentPane().add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 50, -1));
                      getContentPane().add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 50, -1));
                      getContentPane().add(jSpinner5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 50, -1));

                      jLabel7.setText("Empleados disponibles");
                      getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

                      jScrollPane6.setViewportView(jTextPane6);

                      getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, -1));

                      jCheckBox1.setText("40 GB / ");
                      jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            jCheckBox1ActionPerformed(evt);
                                 }
                      });
                      getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 80, -1));

                      jCheckBox2.setText("30 GB /");
                      jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            jCheckBox2ActionPerformed(evt);
                                 }
                      });
                      getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 70, -1));

                      jCheckBox3.setText("25 GB /");
                      jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            jCheckBox3ActionPerformed(evt);
                                 }
                      });
                      getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

                      jCheckBox4.setText("50 GB /");
                      jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            jCheckBox4ActionPerformed(evt);
                                 }
                      });
                      getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

                      jCheckBox5.setText("55 GB /");
                      jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            jCheckBox5ActionPerformed(evt);
                                 }
                      });
                      getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

                      jLabel8.setText("ensambladores");
                      getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));
                      getContentPane().add(jSpinner6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 50, -1));

                      jLabel9.setText("Dias hasta la entrega");
                      getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

                      jScrollPane8.setViewportView(jTextPane8);

                      getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 60, -1));

                      jLabel10.setText("Project Manager");
                      getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

                      jScrollPane9.setViewportView(jTextPane9);

                      getContentPane().add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 240, -1));

                      jLabel11.setText("Director");
                      getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

                      jScrollPane10.setViewportView(jTextPane10);

                      getContentPane().add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 240, -1));

                      jLabel12.setText("Faltas");
                      getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

                      jScrollPane11.setViewportView(jTextPane11);

                      getContentPane().add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 60, -1));

                      jLabel13.setText("Gastos de la planta");
                      getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 120, -1));

                      jLabel14.setText("Salario");
                      getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

                      jScrollPane12.setViewportView(jTextPane12);

                      getContentPane().add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 60, -1));

                      jScrollPane13.setViewportView(jTextPane13);

                      getContentPane().add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 60, -1));

                      Simulacion.setText("Simulacion");
                      Simulacion.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            SimulacionActionPerformed(evt);
                                 }
                      });
                      getContentPane().add(Simulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 120, -1));

                      jLabel15.setText("temporadas");
                      getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

                      jScrollPane14.setViewportView(jTextPane14);

                      getContentPane().add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 90, -1));

                      jLabel16.setText("capitulos");
                      getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

                      jScrollPane15.setViewportView(jTextPane15);

                      getContentPane().add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 90, -1));

                      jLabel17.setText("ganancias (millones)");
                      getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 120, -1));

                      jScrollPane16.setViewportView(jTextPane16);

                      getContentPane().add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 60, -1));

                      jLabel18.setText("Dias por lotes");
                      getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

                      jScrollPane17.setViewportView(jTextPane17);

                      getContentPane().add(jScrollPane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 60, -1));

                      outputPlotTwist.setBackground(new java.awt.Color(204, 255, 255));
                      outputPlotTwist.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      outputPlotTwist.setText("0");
                      getContentPane().add(outputPlotTwist, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 50, 20));

                      outputIntro.setBackground(new java.awt.Color(204, 255, 255));
                      outputIntro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      outputIntro.setText("0");
                      getContentPane().add(outputIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 50, 20));

                      outputCreditos.setBackground(new java.awt.Color(204, 255, 255));
                      outputCreditos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      outputCreditos.setText("0");
                      getContentPane().add(outputCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 50, 20));

                      outputInicio.setBackground(new java.awt.Color(204, 255, 255));
                      outputInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      outputInicio.setText("0");
                      getContentPane().add(outputInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 50, 20));

                      outputCierre.setBackground(new java.awt.Color(204, 255, 255));
                      outputCierre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      outputCierre.setText("0");
                      getContentPane().add(outputCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 50, 20));

                      pack();
           }// </editor-fold>//GEN-END:initComponents

           private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
                      // TODO add your handling code here:
           }//GEN-LAST:event_jCheckBox1ActionPerformed

           private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
                      // TODO add your handling code here:\
                      ProductorIntro pIntro = new ProductorIntro();
                      pIntro.sinDrive();
           }//GEN-LAST:event_jCheckBox2ActionPerformed

           private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
                      // TODO add your handling code here:
           }//GEN-LAST:event_jCheckBox3ActionPerformed

           private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
                      // TODO add your handling code here:
           }//GEN-LAST:event_jCheckBox4ActionPerformed

           private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
                      // TODO add your handling code here:
           }//GEN-LAST:event_jCheckBox5ActionPerformed

           private void SimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimulacionActionPerformed
                      iniciar = true;
                      ProductorIntro pIntro = new ProductorIntro();
 
                      Thread hilo = new Thread(){
                                 public void run(){
                                            for( ; ;){
                                                       if(iniciar == true){
                                                                  try{
                                                                             Thread.sleep(1000);
                                                                             pIntro.introCreada();
                                                                             outputIntro.setText(Integer.toString(pIntro.getIntros()));
                                                                             if(pIntro.getDrive() == 0){
                                                                                        System.out.println(pIntro.getDrive());
                                                                             }else if(pIntro.getIntros() >= pIntro.getDrive()){
                                                                                        break;
                                                                             }
                                                                             
                                                                  }catch(InterruptedException e){
                                                                            
                                                                  }
                                                       }
                                            }
                                 }
                      };hilo.start();
                   
           }//GEN-LAST:event_SimulacionActionPerformed

           /**
            * @param args the command line arguments
            */
           public static void main(String args[]) {
                      /* Set the Nimbus look and feel */
                      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                       */
                      try {
                                 for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                            if ("Nimbus".equals(info.getName())) {
                                                       javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                                       break;
                                            }
                                 }
                      } catch (ClassNotFoundException ex) {
                                 java.util.logging.Logger.getLogger(casaRodaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                      } catch (InstantiationException ex) {
                                 java.util.logging.Logger.getLogger(casaRodaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                      } catch (IllegalAccessException ex) {
                                 java.util.logging.Logger.getLogger(casaRodaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                                 java.util.logging.Logger.getLogger(casaRodaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                      }
                      //</editor-fold>

                      /* Create and display the form */
                      java.awt.EventQueue.invokeLater(new Runnable() {
                                 public void run() {
                                            new casaRodaje().setVisible(true);
                                 }
                      });
           }

           // Variables declaration - do not modify//GEN-BEGIN:variables
           private javax.swing.JButton Simulacion;
           private javax.swing.JCheckBox jCheckBox1;
           private javax.swing.JCheckBox jCheckBox2;
           private javax.swing.JCheckBox jCheckBox3;
           private javax.swing.JCheckBox jCheckBox4;
           private javax.swing.JCheckBox jCheckBox5;
           private javax.swing.JLabel jLabel1;
           private javax.swing.JLabel jLabel10;
           private javax.swing.JLabel jLabel11;
           private javax.swing.JLabel jLabel12;
           private javax.swing.JLabel jLabel13;
           private javax.swing.JLabel jLabel14;
           private javax.swing.JLabel jLabel15;
           private javax.swing.JLabel jLabel16;
           private javax.swing.JLabel jLabel17;
           private javax.swing.JLabel jLabel18;
           private javax.swing.JLabel jLabel2;
           private javax.swing.JLabel jLabel3;
           private javax.swing.JLabel jLabel4;
           private javax.swing.JLabel jLabel5;
           private javax.swing.JLabel jLabel6;
           private javax.swing.JLabel jLabel7;
           private javax.swing.JLabel jLabel8;
           private javax.swing.JLabel jLabel9;
           private javax.swing.JPanel jPanel1;
           private javax.swing.JPanel jPanel2;
           private javax.swing.JScrollPane jScrollPane10;
           private javax.swing.JScrollPane jScrollPane11;
           private javax.swing.JScrollPane jScrollPane12;
           private javax.swing.JScrollPane jScrollPane13;
           private javax.swing.JScrollPane jScrollPane14;
           private javax.swing.JScrollPane jScrollPane15;
           private javax.swing.JScrollPane jScrollPane16;
           private javax.swing.JScrollPane jScrollPane17;
           private javax.swing.JScrollPane jScrollPane6;
           private javax.swing.JScrollPane jScrollPane8;
           private javax.swing.JScrollPane jScrollPane9;
           private javax.swing.JSpinner jSpinner1;
           private javax.swing.JSpinner jSpinner2;
           private javax.swing.JSpinner jSpinner3;
           private javax.swing.JSpinner jSpinner4;
           private javax.swing.JSpinner jSpinner5;
           private javax.swing.JSpinner jSpinner6;
           private javax.swing.JTextPane jTextPane10;
           private javax.swing.JTextPane jTextPane11;
           private javax.swing.JTextPane jTextPane12;
           private javax.swing.JTextPane jTextPane13;
           private javax.swing.JTextPane jTextPane14;
           private javax.swing.JTextPane jTextPane15;
           private javax.swing.JTextPane jTextPane16;
           private javax.swing.JTextPane jTextPane17;
           private javax.swing.JTextPane jTextPane6;
           private javax.swing.JTextPane jTextPane8;
           private javax.swing.JTextPane jTextPane9;
           private javax.swing.JLabel outputCierre;
           private javax.swing.JLabel outputCreditos;
           private javax.swing.JLabel outputInicio;
           private javax.swing.JLabel outputIntro;
           private javax.swing.JLabel outputPlotTwist;
           // End of variables declaration//GEN-END:variables
}
